const messageList = document.querySelector(".chat-box");
const input = document.querySelector(".chat-input input");
const sendButton = document.querySelector(".chat-input button");

const responses = {
    "Inteligência Artificial (IA)": [
        "Inteligência Artificial (IA) foi um termo cunhado por John McCarthy em 1956 durante a Conferência de Dartmouth", 
        "Os sistemas de IA podem ser treinados usando algoritmos de aprendizado supervisionado, não supervisionado e por reforço", 
        "A IA já consegue superar humanos em jogos complexos como xadrez e Go", 
        "Alguns algoritmos de IA conseguem gerar imagens, música e até mesmo textos", 
        "A IA é amplamente usada em áreas como diagnóstico médico, finanças e reconhecimento de fala", 
        "Redes neurais profundas são inspiradas no funcionamento do cérebro humano", 
        "A IA é a base para tecnologias como carros autônomos e assistentes virtuais", 
        "A IA é dividida em IA forte e IA fraca; a IA forte teria a capacidade de pensar e sentir como humanos", 
        "Modelos de IA como ChatGPT são treinados em grandes volumes de dados textuais para gerar respostas coerentes", 
        "Deep learning (aprendizado profundo) é uma das principais técnicas usadas no desenvolvimento de IA moderna", 
        "Algoritmos de IA podem aprender e melhorar com o tempo sem serem reprogramados", 
        "A IA está em constante evolução e ainda há desafios, como o viés algorítmico e a transparência", 
        "A IA está sendo usada para desenvolver novos fármacos e acelerar a descoberta de medicamentos", 
        "Os chatbots de IA são projetados para entender e responder em linguagem natural", 
        "O reconhecimento facial é uma aplicação comum de IA, mas levanta questões de privacidade", 
        "Alguns especialistas acreditam que IA avançada poderá ser uma ameaça à humanidade se não for controlada", 
        "IA pode realizar tarefas repetitivas de forma mais eficiente que humanos", 
        "A IA também está sendo usada para criar sistemas de tradução automática cada vez mais precisos", 
        "Grandes empresas de tecnologia estão investindo bilhões em pesquisa e desenvolvimento de IA", 
        "Em muitos casos, IA já consegue superar humanos em tarefas de análise de dados e reconhecimento de padrões",
        "A IA está avançando em tarefas criativas, como escrever roteiros, criar imagens e até compor música",
        "Algoritmos de IA podem detectar padrões em grandes volumes de dados que são imperceptíveis para humanos",
        "Existem debates sobre ética em IA, especialmente em relação a emprego e privacidade",
        "A IA é usada em segurança cibernética para identificar ameaças e responder a ataques automaticamente",
        "Chatbots com IA são capazes de responder a perguntas frequentes e melhorar o atendimento ao cliente",
        "IA é aplicada em análises preditivas, ajudando a prever tendências de mercado e comportamento do consumidor",
        "Alguns sistemas de IA estão sendo usados para detectar fraudes em transações financeiras",
        "IA já consegue gerar modelos 3D de objetos e rostos a partir de uma única imagem",
        "Algoritmos de IA podem ajustar-se automaticamente a novos dados para melhorar sua precisão",
        "IA está sendo usada na agricultura para prever a produção e controlar pragas de forma mais eficiente",
        "Os modelos de IA são treinados com grandes quantidades de dados para fazer previsões e classificações",
        "Redes neurais profundas são formadas por várias camadas, cada uma extraindo diferentes características dos dados",
        "A pesquisa em IA explora áreas como robótica, processamento de linguagem natural e visão computacional",
        "Existem IAs projetadas para analisar e interpretar imagens de exames médicos com precisão humana",
        "A IA é uma ferramenta chave na personalização de conteúdo em plataformas de streaming",
        "A IA está sendo utilizada em mobilidade urbana para otimizar o fluxo de trânsito e reduzir congestionamentos",
        "Os sistemas de recomendação, como em redes sociais e e-commerce, são movidos por algoritmos de IA",
        "Pesquisadores estudam a transparência e interpretabilidade de IA para entender como os algoritmos tomam decisões",
        "A IA é usada para detectar doenças como câncer, analisando imagens médicas e relatórios clínicos"

    ],
    "Internet das Coisas (IoT)": [
        "A Internet das Coisas (IoT) conecta dispositivos físicos à internet para troca de dados",
        "A IoT permite que aparelhos como geladeiras, lâmpadas e carros se comuniquem entre si",
        "Estima-se que em 2030 haverá mais de 50 bilhões de dispositivos IoT conectados ao redor do mundo",
        "A segurança é uma das maiores preocupações com dispositivos IoT, pois podem ser vulneráveis a ataques",
        "Dispositivos IoT são amplamente usados em casas inteligentes, cidades inteligentes e automação industrial",
        "Sensores IoT podem monitorar desde o clima até a saúde de pacientes em hospitais",
        "A IoT utiliza várias tecnologias, como Wi-Fi, Bluetooth e redes de baixa potência, para conectar dispositivos",
        "Agricultura inteligente usa IoT para monitorar a qualidade do solo, umidade e saúde das plantações",
        "Veículos conectados, como carros e caminhões, usam IoT para monitoramento em tempo real e manutenção preventiva",
        "A IoT possibilita a criação de dispositivos vestíveis, como relógios e pulseiras inteligentes",
        "Os dados coletados por dispositivos IoT ajudam empresas a tomar decisões mais informadas",
        "Algumas cidades usam IoT para controlar iluminação pública e reduzir o consumo de energia",
        "Há regulações emergentes para garantir a segurança e privacidade de dispositivos IoT",
        "Dispositivos IoT podem ser controlados remotamente, permitindo automação e economia de tempo",
        "O uso de IoT na saúde permite o monitoramento remoto de pacientes e melhora o atendimento médico",
        "Indústrias utilizam IoT para manutenção preditiva de máquinas, reduzindo custos de operação",
        "Redes 5G estão impulsionando a expansão da IoT devido à alta velocidade e baixa latência",
        "Alguns especialistas veem a IoT como o futuro da conectividade em quase todos os setores",
        "Dispositivos IoT geram uma enorme quantidade de dados, alimentando análises e aprendizado de máquina",
        "O crescimento da IoT está levando ao desenvolvimento de novas soluções de armazenamento e processamento de dados",
        "A IoT permite monitorar remotamente a saúde de máquinas e equipamentos para prever falhas",
        "Com a IoT, a coleta de dados se torna automatizada, facilitando decisões informadas e rápidas",
        "Dispositivos IoT podem automatizar tarefas domésticas, como ligar luzes e ajustar a temperatura",
        "O desenvolvimento da IoT está impulsionando a demanda por redes de baixa latência e alta capacidade",
        "A IoT é essencial para a criação de ambientes inteligentes em casas, indústrias e cidades",
        "Os dispositivos IoT funcionam através de redes interconectadas, como Wi-Fi, Bluetooth e 5G",
        "O setor de saúde usa IoT para monitoramento remoto de pacientes e gerenciamento de medicamentos",
        "Agricultura de precisão utiliza IoT para otimizar irrigação, monitorar o clima e aumentar a produtividade",
        "Dispositivos IoT, como medidores inteligentes, ajudam a gerenciar o consumo de energia e água",
        "Dispositivos IoT produzem dados que são fundamentais para análise em big data e inteligência artificial",
        "Carros conectados utilizam IoT para navegação em tempo real e para enviar alertas de manutenção",
        "Os dispositivos IoT estão se expandindo para áreas como segurança pública e resposta a emergências",
        "Alguns dispositivos IoT podem funcionar com baterias de longa duração ou até energia solar",
        "O gerenciamento de redes IoT é complexo, pois há muitos dispositivos interagindo simultaneamente",
        "Empresas estão desenvolvendo padrões de segurança para proteger dispositivos IoT contra invasões",
        "A IoT facilita a automação de processos industriais, aumentando a eficiência e reduzindo custos",
        "A análise de dados de IoT em tempo real é usada para detectar anomalias em operações e produtos",
        "A IoT é fundamental para a indústria 4.0, promovendo a automação e a interconexão entre máquinas",
        "Dispositivos vestíveis IoT, como pulseiras de fitness, monitoram dados de saúde e bem-estar"

    ],
    "Computação em Nuvem": [
        "A computação em nuvem permite armazenar e acessar dados e aplicativos pela internet, sem a necessidade de armazenamento local",
        "Os três principais modelos de serviço em nuvem são IaaS (Infraestrutura como Serviço), PaaS (Plataforma como Serviço) e SaaS (Software como Serviço)",
        "Empresas como Amazon, Google e Microsoft são líderes no mercado de computação em nuvem",
        "A computação em nuvem ajuda empresas a reduzir custos com infraestrutura de TI",
        "Com a nuvem, empresas podem escalar seus recursos de computação conforme a demanda aumenta ou diminui",
        "Armazenamento em nuvem permite que usuários acessem seus arquivos de qualquer dispositivo conectado à internet",
        "O conceito de computação em nuvem existe desde a década de 1960, mas só ganhou popularidade nos anos 2000",
        "A nuvem oferece alta disponibilidade, permitindo que os serviços fiquem acessíveis a qualquer momento",
        "A computação em nuvem facilita a colaboração, permitindo que várias pessoas trabalhem nos mesmos documentos em tempo real",
        "Os dados na nuvem geralmente são replicados em vários servidores para garantir segurança e continuidade",
        "Cloud computing é fundamental para tecnologias emergentes como inteligência artificial e big data",
        "A segurança de dados é uma preocupação importante na nuvem, levando a investimentos em criptografia e autenticação",
        "Serviços de nuvem pública compartilham recursos entre vários usuários, enquanto a nuvem privada é usada por uma única organização",
        "Empresas podem optar por uma nuvem híbrida, combinando nuvem pública e privada para diferentes necessidades",
        "A computação em nuvem reduz a necessidade de dispositivos de alto desempenho, já que o processamento pode ser feito remotamente",
        "Backups em nuvem ajudam a proteger dados contra perda acidental ou falhas de hardware",
        "A computação em nuvem permite atualizações automáticas de software, reduzindo o trabalho de manutenção",
        "Com a nuvem, empresas podem operar de maneira mais ágil e responder rapidamente a mudanças no mercado",
        "Armazenamento em nuvem é usado por bilhões de pessoas em serviços populares como Google Drive, Dropbox e iCloud",
        "Pequenas empresas se beneficiam da nuvem, pois podem acessar tecnologias avançadas sem grandes investimentos",
        "A computação em nuvem permite que pequenas empresas acessem infraestrutura de TI avançada a um custo menor",
        "A nuvem pode oferecer backups automáticos, evitando a perda de dados em caso de falhas",
        "Empresas de jogos utilizam a nuvem para armazenar e transmitir dados de jogos multiplayer",
        "Com a nuvem, desenvolvedores podem testar e lançar novos aplicativos rapidamente",
        "A computação em nuvem permite o uso de máquinas virtuais, que podem ser facilmente escaladas",
        "A nuvem suporta tecnologias de big data, permitindo a análise rápida de grandes volumes de dados",
        "Modelos de aprendizado de máquina podem ser treinados em nuvem para reduzir o tempo de processamento",
        "A computação em nuvem é fundamental para aplicativos de streaming e redes sociais em tempo real",
        "Armazenamento em nuvem pode ser expandido ou reduzido conforme a demanda, sem a compra de hardware",
        "A computação em nuvem facilita o acesso a dados de qualquer lugar, aumentando a mobilidade de trabalho",
        "A cloud computing permite a recuperação de dados e a continuidade dos negócios após desastres",
        "Recursos de segurança, como criptografia e autenticação multifator, são comuns em serviços de nuvem",
        "Aplicações de saúde na nuvem facilitam o compartilhamento seguro de registros médicos",
        "A nuvem oferece serviços específicos para desenvolvedores, como análise de dados e machine learning",
        "Empresas podem personalizar e otimizar suas soluções de nuvem para necessidades específicas",
        "Com a nuvem, atualizações de software podem ser feitas em tempo real, sem interrupções",
        "A nuvem permite colaboração simultânea, permitindo que várias pessoas editem um documento ao mesmo tempo",
        "Serviços em nuvem são amplamente utilizados para o armazenamento e análise de dados de IoT",
        "A computação em nuvem é acessível em dispositivos móveis, tablets e desktops, promovendo flexibilidade"
    ],
    "Realidade Virtual (VR) e Realidade Aumentada (AR)": [
        "A Realidade Virtual (VR) cria um ambiente totalmente imersivo, bloqueando o mundo real e transportando o usuário para um ambiente virtual",
        "A Realidade Aumentada (AR) adiciona elementos digitais ao ambiente real, como filtros de câmera e jogos móveis",
        "VR é muito usada em jogos, simulações de voo e treinamentos médicos para criar ambientes realistas",
        "AR é amplamente utilizada em aplicativos móveis como o Pokémon GO e filtros de redes sociais",
        "A combinação de VR e AR é chamada de Realidade Mista (MR), que mistura elementos virtuais com o mundo real de forma interativa",
        "Empresas como Meta (Facebook), Google e Microsoft investem pesado em tecnologia VR e AR",
        "A AR é popular em varejo, permitindo que clientes experimentem móveis ou roupas de forma virtual antes de comprar",
        "VR é usada em terapias para tratar fobias e ansiedade, expondo pacientes a situações controladas e seguras",
        "O primeiro conceito de VR foi explorado nos anos 1960, mas a tecnologia só avançou nos últimos anos",
        "Headsets de VR, como o Oculus Quest e PlayStation VR, aumentaram a popularidade da tecnologia de VR para o público em geral",
        "AR em dispositivos móveis é possível graças a sensores como câmeras, GPS e acelerômetros",
        "Ambientes de VR exigem altas taxas de atualização para evitar náuseas e melhorar a experiência de imersão",
        "A AR já é usada em educação para criar experiências interativas de aprendizado em sala de aula",
        "Realidade Virtual pode ajudar em treinamentos militares, permitindo simulações de combate seguras",
        "Arquitetos usam VR para criar simulações imersivas de projetos antes mesmo da construção",
        "Aplicativos de AR podem reconhecer objetos e traduzi-los em informações em tempo real, como tradução de placas",
        "Na área da saúde, VR é usada para treinar cirurgias complexas e simular procedimentos médicos",
        "AR é usada para orientações em tempo real, como navegação em mapas e informações em eventos esportivos",
        "Headsets de VR são equipados com rastreamento de movimento para detectar a posição do usuário no ambiente virtual",
        "Realidade Aumentada está se tornando comum em museus para fornecer informações adicionais sobre exposições",
        "Empresas usam VR para criar ambientes de trabalho virtuais e reuniões remotas mais interativas",
        "AR pode ser usada em manutenção industrial, ajudando técnicos a visualizar componentes complexos em equipamentos",
        "Os conceitos de VR e AR são baseados na percepção de presença, permitindo que o usuário sinta que está realmente em outro lugar",
        "Plataformas de redes sociais estão integrando AR para interações e conteúdos mais dinâmicos",
        "A VR pode induzir um estado conhecido como 'presença', onde o usuário sente estar fisicamente em um ambiente virtual",
        "Realidade Aumentada está presente em dispositivos de assistência, como óculos de tradução e guias de viagem",
        "A indústria imobiliária usa VR para criar visitas virtuais a imóveis para potenciais compradores",
        "VR e AR podem reduzir custos em treinamentos e educação, pois oferecem experiências realistas sem necessidade de locação física",
        "AR está sendo usada em veículos para mostrar informações diretamente no para-brisa, como velocidade e instruções de GPS",
        "Headsets de VR continuam evoluindo, tornando-se mais leves e acessíveis, com gráficos de alta qualidade",
        "AR pode ajudar deficientes visuais a navegar no ambiente com informações visuais e sonoras adicionais",
        "Realidade Virtual ainda enfrenta desafios, como a 'síndrome da visão de túnel', que pode causar desconforto visual",
        "Aplicações de AR estão crescendo em medicina, permitindo que cirurgiões vejam camadas de tecido em tempo real",
        "Ambientes virtuais em VR ajudam a reabilitar pacientes com dificuldades motoras e neurológicas",
        "A VR oferece imersão em jogos 360 graus, onde o jogador pode interagir com o ambiente ao redor",
        "A tecnologia AR em dispositivos móveis pode transformar quase qualquer lugar em um espaço interativo",
        "Em VR, o controle dos movimentos é essencial, e muitos headsets possuem controladores de mão para interação",
        "A evolução da VR e AR é esperada para transformar setores inteiros, desde entretenimento até o ensino",
        "Os displays de AR em óculos podem sobrepor gráficos úteis para trabalhadores em tempo real, como esquemas técnicos",
        "VR é usada por psicólogos para criar ambientes seguros onde os pacientes podem enfrentar medos e fobias",
        "A segurança cibernética é uma preocupação crescente em AR, pois dados do mundo real estão cada vez mais integrados",
        "A AR está se expandindo no marketing, com experiências interativas para que os clientes conheçam produtos"

    ],
    "Cibersegurança": [
        "A Cibersegurança protege sistemas e dados contra acessos não autorizados, ataques e danos",
        "Phishing é uma das formas mais comuns de ataque, onde golpistas tentam enganar as pessoas para roubar informações",
        "Senhas fortes e autenticação multifator são medidas básicas, mas essenciais, de segurança cibernética",
        "Os ataques de ransomware bloqueiam o acesso a dados até que um resgate seja pago ao invasor",
        "A criptografia transforma dados em códigos, protegendo informações confidenciais em trânsito e em repouso",
        "Cibersegurança inclui práticas de segurança em redes, aplicações, e infraestrutura da internet",
        "A educação em cibersegurança é fundamental, pois muitos ataques exploram erros humanos",
        "A engenharia social é uma técnica comum em ataques, explorando a confiança para obter informações",
        "Firewalls e antivírus ajudam a proteger contra malwares e acessos indesejados a dispositivos",
        "Grandes empresas sofrem ataques cibernéticos frequentemente, e os danos podem ser milionários",
        "Zero Trust é uma abordagem de segurança que exige verificação constante, independente da origem do acesso",
        "A conformidade com regulamentos, como GDPR, é essencial para proteger dados de usuários e evitar multas",
        "Os ataques DDoS sobrecarregam sites com tráfego, fazendo com que fiquem indisponíveis para os usuários",
        "Dispositivos de IoT são vulneráveis e, quando comprometidos, podem ser usados em ataques em larga escala",
        "Cibersegurança é uma das áreas de TI com mais crescimento de emprego devido ao aumento dos ciberataques",
        "As ameaças de cibersegurança evoluem constantemente, exigindo que as empresas adaptem suas defesas",
        "A computação em nuvem requer práticas específicas de segurança para proteger dados e recursos remotos",
        "O uso de redes Wi-Fi públicas pode ser arriscado, pois facilita o acesso de invasores a dados pessoais",
        "Crimes cibernéticos podem ser realizados por indivíduos isolados, grupos organizados ou até governos",
        "Pentests são testes de invasão realizados por especialistas para identificar vulnerabilidades de sistemas",
        "Algoritmos de aprendizado de máquina são usados para identificar atividades suspeitas em redes",
        "A resposta a incidentes é um campo da cibersegurança que lida com a contenção e recuperação de ataques",
        "Os hackers éticos ajudam a identificar brechas e aumentar a segurança dos sistemas antes que sejam explorados",
        "Empresas mantêm backups para proteger dados importantes e garantir a recuperação após um ataque",
        "Os ataques de Man-in-the-Middle (MitM) interceptam a comunicação entre duas partes para roubar dados",
        "Roubo de identidade digital é uma das consequências comuns de ataques de cibersegurança",
        "As ameaças internas, como funcionários mal-intencionados, são um grande risco para a cibersegurança",
        "O uso de inteligência artificial está facilitando a detecção de ameaças em tempo real",
        "Os ataques cibernéticos estão se tornando mais sofisticados, exigindo defesas avançadas",
        "A política de privacidade nas redes sociais ajuda a proteger informações pessoais contra exploração",
        "Um SOC (Centro de Operações de Segurança) monitora e responde a ameaças em tempo real em empresas",
        "O roubo de dados pode afetar negativamente a reputação das empresas e a confiança do consumidor",
        "Segurança cibernética se aplica a todos, desde indivíduos até grandes corporações e governos",
        "Os ataques direcionados, como spear phishing, são altamente personalizados e difíceis de detectar",
        "Estima-se que o custo global do cibercrime atingirá trilhões de dólares nos próximos anos",
        "A falta de atualizações de software é uma das principais causas de vulnerabilidades em sistemas",
        "A automação na cibersegurança ajuda a responder a ameaças rapidamente e a reduzir o trabalho manual",
        "Nosso comportamento online pode afetar nossa segurança; é essencial não compartilhar dados confidenciais"

    ],
    "Blockchain e Criptomoedas": [
        "Blockchain é uma tecnologia de registro distribuído que armazena dados de forma transparente e segura",
        "O Bitcoin, lançado em 2009, foi a primeira criptomoeda e ainda é a mais conhecida e valiosa",
        "Uma blockchain é composta por blocos encadeados que contêm dados e são protegidos por criptografia",
        "Blockchain é descentralizada, o que significa que não depende de uma autoridade central para validar transações",
        "Criptomoedas são ativos digitais que utilizam criptografia para garantir transações seguras e descentralizadas",
        "O Ethereum é a segunda maior criptomoeda e permite a criação de contratos inteligentes na blockchain",
        "Contratos inteligentes são programas autônomos na blockchain que executam ações automaticamente",
        "A mineração de criptomoedas envolve resolver problemas matemáticos complexos para validar transações",
        "O Bitcoin tem um suprimento limitado de 21 milhões de moedas, o que ajuda a controlar a inflação",
        "Cada transação em uma blockchain é registrada em todos os nós da rede, tornando-a imutável",
        "A tecnologia de blockchain é utilizada em várias áreas além das criptomoedas, como supply chain e saúde",
        "Blockchain fornece transparência, pois qualquer pessoa pode visualizar o histórico de transações",
        "A mineração consome grande quantidade de energia, especialmente em blockchains que utilizam prova de trabalho (PoW)",
        "A prova de participação (PoS) é uma alternativa à mineração, que consome menos energia",
        "As transações de criptomoedas são geralmente mais rápidas e baratas do que transferências bancárias tradicionais",
        "Os NFTs (Tokens Não Fungíveis) são ativos digitais únicos criados em blockchains como Ethereum",
        "As carteiras digitais armazenam chaves privadas, que permitem o acesso e a transação de criptomoedas",
        "Bitcoin é frequentemente chamado de 'ouro digital' por seu valor como reserva e proteção contra a inflação",
        "Blockchains públicas são acessíveis a qualquer pessoa, enquanto blockchains privadas exigem permissão",
        "A segurança das blockchains é garantida por criptografia, mas a proteção das chaves privadas é essencial",
        "As stablecoins são criptomoedas com valor atrelado a um ativo estável, como o dólar, para reduzir a volatilidade",
        "Blockchain permite a criação de DeFi (Finanças Descentralizadas), um sistema financeiro sem bancos tradicionais",
        "Tokens de utilidade e tokens de governança são usados em blockchain para representar acesso a serviços e decisões",
        "A blockchain permite o rastreamento de produtos na cadeia de suprimentos, garantindo a autenticidade",
        "Criptomoedas são armazenadas em carteiras digitais, que podem ser online (hot wallets) ou offline (cold wallets)",
        "A adoção de criptomoedas está crescendo globalmente, especialmente em países com inflação elevada",
        "Uma transação em blockchain é irreversível; uma vez registrada, não pode ser alterada ou apagada",
        "As exchanges de criptomoedas permitem a compra, venda e troca de criptomoedas entre usuários",
        "Alguns governos estão explorando moedas digitais próprias, conhecidas como CBDCs (Moedas Digitais do Banco Central)",
        "A segurança da blockchain vem de sua estrutura distribuída e do consenso entre os participantes da rede",
        "As criptomoedas podem ser voláteis, com grandes variações de preço em curtos períodos de tempo",
        "Existem milhares de criptomoedas, e cada uma pode ter diferentes finalidades e tecnologias subjacentes",
        "As chaves privadas são essenciais para a posse de criptomoedas, e sua perda significa a perda dos ativos",
        "Blockchain é considerada uma tecnologia de registro confiável devido à sua transparência e segurança",
        "Tokens em blockchain podem representar ativos físicos, como imóveis ou obras de arte, em formato digital",
        "As criptomoedas podem facilitar pagamentos internacionais sem taxas de câmbio e demoras bancárias",
        "Criptomoedas e blockchain estão mudando a forma como entendemos e utilizamos o dinheiro e os contratos",
        "Alguns críticos de criptomoedas apontam preocupações com a lavagem de dinheiro e evasão fiscal",
        "Bitcoin foi criado pelo misterioso Satoshi Nakamoto, cuja identidade permanece desconhecida até hoje",
        "Os forks ocorrem quando há mudanças no protocolo de uma blockchain, criando novas versões, como Bitcoin e Bitcoin Cash"

    ],
    "Big Data e Análise de Dados": [
        "Big Data refere-se a grandes volumes de dados que são gerados em alta velocidade e em diversos formatos",
        "A análise de dados em Big Data ajuda empresas a tomar decisões informadas e baseadas em dados",
        "Big Data é frequentemente descrito pelos 5 Vs: Volume, Variedade, Velocidade, Veracidade e Valor",
        "Ferramentas como Hadoop e Spark são populares para processar e analisar grandes volumes de dados",
        "A análise preditiva usa Big Data para prever tendências e comportamentos futuros com base em dados históricos",
        "A coleta de dados em tempo real permite que as empresas respondam rapidamente às mudanças de mercado",
        "Big Data é utilizado em áreas como marketing, saúde, segurança e entretenimento",
        "A mineração de dados é uma técnica que explora grandes conjuntos de dados para identificar padrões ocultos",
        "Os dados são coletados de várias fontes, como redes sociais, transações, sensores e dispositivos IoT",
        "Machine Learning é uma ferramenta essencial em Big Data para treinar modelos em grandes volumes de dados",
        "A análise de Big Data ajuda a personalizar ofertas e melhorar a experiência do cliente",
        "A governança de dados é importante para garantir que os dados sejam precisos, seguros e usados de forma ética",
        "Os cientistas de dados são profissionais que usam habilidades analíticas para interpretar dados complexos",
        "A análise de sentimentos em redes sociais usa Big Data para entender as opiniões dos consumidores",
        "O processamento de linguagem natural (NLP) é usado em Big Data para analisar textos e reconhecer padrões",
        "Big Data em saúde ajuda a prever surtos de doenças e personalizar tratamentos para pacientes",
        "Com a análise de dados, empresas conseguem otimizar seus processos e reduzir custos",
        "Data Lakes são repositórios que armazenam dados não estruturados em grande volume para análise posterior",
        "Big Data permite a detecção de fraudes em tempo real, analisando transações suspeitas",
        "A análise prescritiva usa dados para sugerir ações e otimizar processos de decisão",
        "A qualidade dos dados é crucial; dados incorretos podem levar a decisões erradas e ineficientes",
        "A visualização de dados transforma informações complexas em gráficos e relatórios de fácil interpretação",
        "Análise de dados em tempo real é essencial em setores como finanças e logística",
        "Big Data é usado na manutenção preditiva para prever falhas em equipamentos e prevenir interrupções",
        "Dados não estruturados, como texto e vídeo, representam a maior parte dos dados em Big Data",
        "A veracidade dos dados é um desafio, pois os dados podem ser incompletos ou inconsistentes",
        "Empresas utilizam Big Data para segmentar clientes e criar campanhas de marketing direcionadas",
        "A análise de dados pode identificar padrões de comportamento de clientes e prever suas necessidades",
        "Big Data é uma fonte importante para a inteligência artificial, fornecendo dados para treinamento de modelos",
        "A anonimização de dados é uma prática para proteger a privacidade dos indivíduos em análise de dados",
        "O uso de Big Data está crescendo com a expansão de dispositivos conectados e da Internet das Coisas",
        "Os insights obtidos de Big Data ajudam a identificar novas oportunidades de negócio",
        "Empresas de e-commerce utilizam Big Data para recomendar produtos com base no histórico de compras",
        "Na área de segurança, Big Data é usado para monitorar atividades suspeitas e identificar ameaças",
        "A análise de Big Data é uma vantagem competitiva, permitindo que empresas antecipem tendências de mercado",
        "Os dados em Big Data podem ser estruturados (em tabelas) ou não estruturados (como texto e imagens)",
        "Automação em análise de dados facilita o processamento de dados em grande escala com menos intervenção humana",
        "A ética em Big Data é uma questão importante, pois envolve o uso responsável dos dados das pessoas",
        "Big Data permite simulações complexas, ajudando a prever cenários em áreas como finanças e ciência",
        "A análise de dados comportamentais permite prever o engajamento dos clientes com base em suas ações",
        "Grandes volumes de dados são frequentemente armazenados em nuvem para facilitar o acesso e o processamento",
        "A análise de Big Data ajuda a melhorar a precisão em diagnósticos e tratamentos personalizados na medicina",
        "Big Data é usado por governos para melhorar serviços públicos e responder a necessidades sociais",
        "A análise de redes sociais permite prever tendências e entender o impacto de campanhas de mídia"

    ],
    "Tecnologia 5G e Conectividade": [
        "A tecnologia 5G oferece velocidades até 100 vezes maiores que o 4G, permitindo downloads quase instantâneos",
        "5G utiliza frequências mais altas, como ondas milimétricas, para transmitir grandes volumes de dados rapidamente",
        "A baixa latência do 5G permite aplicações em tempo real, como cirurgias remotas e carros autônomos",
        "O 5G possibilita o aumento da conectividade para dispositivos de Internet das Coisas (IoT) em larga escala",
        "As redes 5G podem suportar até um milhão de dispositivos conectados por quilômetro quadrado",
        "O 5G é essencial para a expansão de cidades inteligentes, onde sensores e dispositivos estão conectados em rede",
        "Essa tecnologia melhora a experiência em realidade virtual (VR) e realidade aumentada (AR), com menos atrasos",
        "A latência do 5G pode ser inferior a 1 milissegundo, ideal para aplicações críticas e sensíveis ao tempo",
        "O 5G suporta diferentes níveis de serviço, permitindo o ajuste da rede conforme as necessidades dos usuários",
        "A cobertura de ondas milimétricas do 5G é mais limitada, exigindo mais antenas e infraestrutura",
        "O 5G permite conexões de alta velocidade em áreas densamente povoadas, como estádios e centros urbanos",
        "Com o 5G, redes privadas podem ser criadas para empresas e indústrias, oferecendo maior segurança e controle",
        "O 5G é fundamental para a Indústria 4.0, permitindo comunicação em tempo real entre máquinas e sistemas",
        "A tecnologia 5G pode viabilizar novos modelos de negócios em áreas como saúde, transporte e educação",
        "5G utiliza o slicing de rede, que permite dividir a rede em 'fatias' para diferentes aplicações simultâneas",
        "Em segurança pública, o 5G permite monitoramento e resposta rápida em tempo real através de câmeras conectadas",
        "O 5G vai impulsionar o mercado de carros autônomos, pois possibilita a comunicação instantânea entre veículos",
        "Com o 5G, o consumo de bateria em dispositivos IoT pode ser reduzido, aumentando a vida útil dos sensores",
        "As operadoras de telecomunicações estão investindo bilhões em infraestrutura para expandir o 5G globalmente",
        "Com o 5G, a qualidade das chamadas de vídeo melhora, mesmo em áreas com alta densidade de usuários",
        "O 5G facilita telemedicina em áreas remotas, permitindo consultas e até procedimentos médicos à distância",
        "A tecnologia 5G tem desafios de segurança, pois o aumento de dispositivos conectados amplia a superfície de ataque",
        "Redes 5G privadas estão sendo implementadas em fábricas para automação e controle de equipamentos em tempo real",
        "A cobertura 5G é expandida gradualmente, pois requer novas antenas e investimento em infraestrutura",
        "5G pode impactar positivamente o setor agrícola, conectando sensores para monitorar o solo e o clima",
        "O impacto ambiental do 5G está sendo estudado, pois a alta densidade de antenas pode afetar o consumo de energia",
        "Redes 5G e edge computing funcionam juntas para processar dados perto de onde são gerados, reduzindo latência",
        "O 5G oferece uma conectividade mais estável para veículos, drones e robôs operados remotamente",
        "A popularização do 5G pode transformar o uso da internet móvel, permitindo experiências mais imersivas",
        "A adoção do 5G está acelerando o desenvolvimento de dispositivos compatíveis, como smartphones e wearables",
        "Em jogos online, o 5G melhora a experiência de jogo, eliminando atrasos e oferecendo transmissões em alta resolução",
        "O 5G pode facilitar a educação a distância com transmissão ao vivo em alta definição e baixa latência",
        "A implementação do 5G requer infraestrutura avançada, como pequenas células e antenas distribuídas",
        "Com o 5G, a transferência de dados entre dispositivos é rápida o suficiente para suportar monitoramento em tempo real",
        "O 5G pode aumentar a inclusão digital ao fornecer internet de alta velocidade em áreas rurais",
        "Redes 5G podem ser configuradas para priorizar serviços de emergência em situações de crise",
        "A velocidade do 5G é comparável à de muitas conexões de internet a cabo, promovendo a substituição de redes fixas",
        "O desenvolvimento do 5G incentiva a criação de aplicativos e serviços inovadores, aproveitando a alta velocidade",
        "Dispositivos conectados em 5G podem se comunicar entre si sem depender de uma rede centralizada",
        "Com o 5G, a computação em nuvem pode ser mais eficaz, facilitando o uso de aplicações complexas em dispositivos leves",
        "O 5G facilita a criação de redes de sensores em tempo real para monitoramento ambiental e controle climático",
        "A conectividade 5G pode melhorar a logística, permitindo rastreamento preciso de mercadorias e otimização de rotas",
        "5G permite transmissões ao vivo de alta qualidade em ambientes esportivos e eventos com grande público",
        "O 5G está promovendo avanços na realidade estendida, com AR e VR mais acessíveis e envolventes",
        "A tecnologia 5G é uma das bases para o desenvolvimento de redes e sistemas de comunicação do futuro",
        "A adoção do 5G requer o uso de novas frequências, como bandas sub-6 GHz e ondas milimétricas"

    ],
    "Robótica e Automação": [
        "A robótica combina engenharia mecânica, elétrica e ciência da computação para criar máquinas inteligentes",
        "A automação permite que tarefas repetitivas sejam realizadas por máquinas, aumentando a eficiência e reduzindo erros",
        "Os robôs industriais são usados em fábricas para montagem, soldagem, pintura e outras tarefas precisas",
        "Robôs colaborativos, ou cobots, trabalham ao lado de humanos em ambientes seguros e são programáveis para diversas tarefas",
        "A automação é amplamente usada na produção em massa, como em linhas de montagem de automóveis",
        "A robótica médica permite cirurgias assistidas por robôs, oferecendo maior precisão e controle aos cirurgiões",
        "Robôs móveis, como drones e veículos autônomos, podem explorar e realizar tarefas em ambientes perigosos",
        "A automação residencial, ou domótica, integra sistemas como iluminação e segurança em casas inteligentes",
        "Os robôs humanoides são projetados para se parecer e interagir com humanos, imitando movimentos e expressões",
        "Robôs de resgate são desenvolvidos para ajudar em desastres naturais e missões de salvamento",
        "Sistemas de automação utilizam sensores para monitorar variáveis como temperatura, pressão e movimento",
        "A automação de processos robóticos (RPA) permite que softwares realizem tarefas administrativas repetitivas",
        "Robôs submarinos são utilizados para exploração e pesquisa em profundidades inacessíveis aos humanos",
        "O uso de inteligência artificial permite que robôs aprendam e se adaptem a novas tarefas e ambientes",
        "A robótica está transformando a agricultura com máquinas automatizadas para plantio, colheita e monitoramento",
        "Automação na área de logística permite o transporte eficiente de mercadorias em armazéns e centros de distribuição",
        "Robôs cirúrgicos, como o Da Vinci, são usados em procedimentos minimamente invasivos em hospitais",
        "A robótica de enxame explora a coordenação de múltiplos robôs para realizar tarefas complexas coletivamente",
        "A automação industrial está avançando com a Indústria 4.0, integrando sistemas físicos e digitais",
        "Os drones são amplamente usados para monitoramento aéreo, entrega de pacotes e fotografia",
        "Robôs de limpeza, como aspiradores automáticos, estão se tornando comuns em residências e escritórios",
        "Sistemas de visão computacional permitem que robôs reconheçam objetos e naveguem por ambientes complexos",
        "A robótica espacial permite a exploração de outros planetas, com robôs como o Rover em Marte",
        "Automação em redes elétricas ajuda a monitorar e ajustar a distribuição de energia de forma eficiente",
        "Robôs assistentes, como robôs de telepresença, permitem a interação remota em conferências e consultas médicas",
        "Robôs de pintura são usados na indústria para aplicar camadas uniformes em superfícies de forma precisa",
        "A robótica e automação estão cada vez mais presentes no setor de serviços, como restaurantes e hotéis",
        "A robótica educacional ajuda estudantes a aprenderem programação e princípios de engenharia",
        "Robôs de inspeção monitoram infraestruturas, como pontes e oleodutos, para detectar problemas precocemente",
        "Automação em agricultura, como tratores autônomos, aumenta a produtividade e reduz o desperdício",
        "Robôs de segurança podem patrulhar áreas e reportar atividades suspeitas em tempo real",
        "A robótica de reabilitação auxilia pacientes em tratamentos físicos e recuperação de movimentos",
        "A automação de processos empresariais ajuda a reduzir custos operacionais e aumentar a produtividade",
        "Robôs de entrega estão sendo testados para levar pacotes e alimentos diretamente até o consumidor",
        "Automação e robótica reduzem o risco de acidentes de trabalho ao realizarem tarefas perigosas",
        "A robótica subaquática permite a exploração de naufrágios e pesquisa em ecossistemas marinhos",
        "Robôs educacionais incentivam o aprendizado de STEM (Ciência, Tecnologia, Engenharia e Matemática)",
        "A robótica social cria robôs capazes de interagir emocionalmente, ajudando em áreas como saúde mental",
        "Robôs de construção podem construir estruturas como pontes e casas usando impressão 3D",
        "Automação de testes de software garante que programas funcionem corretamente antes de serem lançados",
        "A robótica exoesquelética oferece suporte a pessoas com limitações de mobilidade",
        "Robôs de armazém, como os da Amazon, movimentam e organizam produtos automaticamente",
        "A automação bancária inclui caixas eletrônicos e sistemas de atendimento automatizado",
        "Os avanços em robótica e automação estão aumentando a eficiência na cadeia de suprimentos global",
        "Robôs de aprendizado autônomo usam dados para melhorar continuamente sua eficiência em tarefas específicas",
        "Robôs em hospitais podem desinfetar salas e transportar medicamentos e materiais de forma autônoma",
        "A robótica na indústria de alimentos facilita o processo de embalagem, rotulagem e distribuição de produtos",
        "A robótica tem potencial para resolver problemas globais, como a escassez de mão de obra em certas indústrias"
    ],
    "Tecnologia Sustentável e Energia Renovável": [
        "A energia solar é uma das fontes de energia renovável mais promissoras, convertendo luz solar em eletricidade",
        "Os painéis solares fotovoltaicos têm a capacidade de gerar eletricidade sem emissão de gases de efeito estufa",
        "A energia eólica utiliza a força do vento para gerar eletricidade e tem uma das maiores capacidades de crescimento no mundo",
        "A energia hidrelétrica é uma das fontes de energia renovável mais antigas e é responsável por grande parte da eletricidade mundial",
        "A biomassa utiliza resíduos orgânicos, como madeira e lixo agrícola, para gerar energia sustentável",
        "A energia geotérmica aproveita o calor interno da Terra para gerar eletricidade e aquecer ambientes",
        "Os biocombustíveis, como o etanol e o biodiesel, são produzidos a partir de plantas e podem substituir combustíveis fósseis",
        "A energia solar térmica utiliza a radiação solar para aquecer água ou outros fluidos, sendo usada em sistemas de aquecimento de água",
        "Em sistemas de energia renovável, a armazenagem de energia é feita por baterias e outras tecnologias, permitindo o uso contínuo",
        "A eficiência energética busca reduzir o consumo de energia sem sacrificar o desempenho dos sistemas ou dispositivos",
        "A reciclagem de materiais é uma tecnologia sustentável importante, reduzindo a extração de recursos naturais e a quantidade de resíduos",
        "Edifícios ecológicos, ou 'green buildings', utilizam tecnologias sustentáveis para reduzir consumo de energia e melhorar a qualidade ambiental",
        "A agricultura sustentável utiliza práticas que não esgotam os recursos naturais e preservam a biodiversidade",
        "A energia das ondas e marés é uma fonte renovável em desenvolvimento, utilizando o movimento da água para gerar eletricidade",
        "A mobilidade elétrica, como os carros elétricos, reduz a dependência de combustíveis fósseis e as emissões de CO2",
        "Os telhados verdes, cobertos com vegetação, ajudam a isolar os edifícios e a reduzir o consumo de energia para resfriamento",
        "Os sistemas de captura e armazenamento de carbono (CCS) capturam CO2 da atmosfera e o armazenam de forma segura",
        "A construção de usinas solares e parques eólicos em locais estratégicos tem o potencial de fornecer eletricidade limpa para milhões de pessoas",
        "A energia renovável pode ser distribuída de maneira descentralizada, permitindo que pequenas comunidades gerem sua própria eletricidade",
        "A impressão 3D está sendo utilizada para criar produtos e componentes de forma mais eficiente e com menos desperdício de material",
        "Os sistemas de iluminação LED consomem muito menos energia em comparação com as lâmpadas incandescentes tradicionais",
        "A energia renovável pode ajudar a reduzir a dependência de combustíveis fósseis e combater as mudanças climáticas",
        "O hidrogênio verde, produzido a partir de fontes renováveis, é considerado uma alternativa limpa aos combustíveis fósseis",
        "A eficiência na produção e distribuição de alimentos também contribui para a sustentabilidade, reduzindo o desperdício de recursos",
        "A aquecimento e resfriamento passivo utiliza a arquitetura e design para reduzir a necessidade de sistemas de climatização mecânica",
        "A sustentabilidade no setor de moda busca minimizar o impacto ambiental por meio de tecidos ecológicos e práticas de produção éticas",
        "A energia solar concentrada usa espelhos e lentes para concentrar a luz solar em um ponto para gerar eletricidade",
        "Veículos solares e elétricos estão se tornando mais acessíveis e eficientes, contribuindo para a redução de emissões de gases",
        "A agricultura urbana é uma solução sustentável para produzir alimentos frescos e reduzir o impacto ambiental da logística de transporte",
        "As turbinas eólicas offshore, instaladas no mar, têm um grande potencial para gerar energia limpa em larga escala",
        "A energia renovável pode ser usada para desalinizar água do mar, fornecendo soluções para a escassez de água em regiões secas",
        "A reciclagem de água e o tratamento eficiente de águas residuais são práticas sustentáveis que economizam recursos hídricos",
        "A produção de energia em pequena escala, como painéis solares domésticos, ajuda as famílias a reduzir seus custos de energia",
        "O uso de tecnologias limpas em indústrias reduz a emissão de poluentes e aumenta a eficiência da produção",
        "A energia renovável contribui para a criação de empregos verdes em setores como construção de parques eólicos e manutenção de painéis solares",
        "A sustentabilidade digital envolve a redução do impacto ambiental das tecnologias, como melhorar a eficiência dos data centers",
        "A economia circular promove o uso de produtos reciclados e o reaproveitamento de materiais, evitando o desperdício",
        "O uso de vegetação nas cidades, como árvores e jardins verticais, ajuda a reduzir o consumo de energia e melhora a qualidade do ar",
        "A energia renovável pode ser combinada com tecnologias de blockchain para criar mercados de energia descentralizados e mais eficientes",
        "Plantas e algas podem ser usadas para capturar CO2 da atmosfera e produzir bioenergia de forma sustentável",
        "A eficiência na utilização dos recursos naturais é fundamental para a construção de um futuro sustentável e de baixo carbono",
        "O design de produtos sustentáveis considera todo o ciclo de vida do produto, desde a fabricação até o descarte ou reutilização"

    ],
    "Computação Quântica": [
        "A computação quântica explora os princípios da mecânica quântica, como superposição e entrelaçamento, para resolver problemas complexos",
        "Em um computador quântico, os bits tradicionais são substituídos pelos qubits, que podem representar vários estados ao mesmo tempo",
        "Os qubits podem estar em uma superposição de 0 e 1 simultaneamente, permitindo uma quantidade exponencial de processamento paralelo",
        "Entrelançamento quântico é um fenômeno onde dois ou mais qubits estão interligados, de modo que o estado de um afeta instantaneamente o estado do outro",
        "A computação quântica tem o potencial de resolver problemas em minutos que levariam anos em computadores tradicionais",
        "Algoritmos quânticos, como o algoritmo de Shor, podem quebrar a criptografia de chave pública utilizada em sistemas de segurança tradicionais",
        "Em uma máquina quântica, a interferência quântica é usada para amplificar as soluções corretas e cancelar as erradas",
        "Os computadores quânticos podem acelerar simulações de moléculas e reações químicas, revolucionando a química e a farmacologia",
        "A computação quântica é um campo emergente, com grandes empresas como Google, IBM e Microsoft investindo pesadamente no desenvolvimento de tecnologias quânticas",
        "A computação quântica pode ser aplicada em áreas como otimização, inteligência artificial e segurança cibernética",
        "Supercondutores e íons aprisionados são algumas das tecnologias usadas para construir qubits em sistemas de computação quântica",
        "A decoerência quântica, onde um qubit perde sua superposição devido a interações com o ambiente, é um dos maiores desafios na construção de computadores quânticos estáveis",
        "Algoritmos quânticos podem melhorar a eficiência de processos de aprendizado de máquina, oferecendo soluções mais rápidas e precisas",
        "Computadores quânticos poderiam ser usados para otimizar problemas logísticos, como o gerenciamento de rotas e cadeias de suprimentos",
        "A criptografia quântica usa os princípios da mecânica quântica para criar sistemas de segurança praticamente invioláveis",
        "Simulações quânticas podem ajudar a projetar novos materiais e desenvolver medicamentos de forma mais eficaz",
        "O armazenamento de informações em qubits pode permitir a criação de computadores de altíssima capacidade, com enormes potenciais de processamento",
        "A computação quântica pode revolucionar a inteligência artificial ao permitir que redes neurais quânticas sejam usadas para resolver problemas complexos",
        "Pesquisas atuais buscam maneiras de melhorar a correção de erros quânticos, um dos maiores obstáculos para a escalabilidade da computação quântica",
        "A computação quântica ainda está em um estágio inicial, e sua aplicação em grande escala pode levar anos, mas já está mostrando grande potencial",
        "O uso de qubits topológicos está sendo explorado como uma forma de reduzir os erros em computadores quânticos",
        "Os algoritmos quânticos podem melhorar a busca em grandes bancos de dados, acelerando processos como recomendações e detecção de padrões",
        "A computação quântica tem o potencial de transformar a ciência de materiais, permitindo a descoberta de novos materiais com propriedades específicas",
        "Computadores quânticos poderiam ser usados para desenvolver novas tecnologias em áreas como inteligência artificial, simulações físicas e previsões climáticas",
        "Os avanços em computação quântica podem permitir a construção de sistemas de IA mais poderosos e eficientes",
        "A computação quântica também pode acelerar a resolução de problemas matemáticos complexos que são difíceis para computadores tradicionais",
        "A segurança quântica promete criar uma nova geração de sistemas de proteção de dados, resistentes a ataques de computadores quânticos",
        "Pesquisadores estão desenvolvendo computação quântica de rede, onde computadores quânticos estão interconectados para resolver problemas em conjunto",
        "Com a computação quântica, é possível melhorar a previsão do comportamento de sistemas complexos, como os sistemas financeiros e o clima",
        "O desenvolvimento da computação quântica pode levar a uma revolução na indústria de processamento de dados e inteligência artificial",
        "O potencial da computação quântica é comparável ao impacto que a computação clássica teve no mundo moderno"

    ],
    "Biotecnologia": [
        "A biotecnologia utiliza organismos vivos, células e sistemas biológicos para desenvolver produtos e processos inovadores",
        "A biotecnologia pode ser aplicada em diversas áreas, como saúde, agricultura, alimentos e meio ambiente",
        "A engenharia genética permite a modificação de organismos para melhorar suas características, como resistência a doenças ou aumento de produtividade",
        "Um exemplo de biotecnologia aplicada à medicina é a produção de medicamentos como insulina, obtida por engenharia genética de bactérias",
        "Os organismos geneticamente modificados (OGMs) são usados para aumentar a resistência de culturas agrícolas a pragas e doenças",
        "A biotecnologia verde é aplicada na agricultura, criando plantas mais resistentes, nutritivas e adaptadas a diferentes condições climáticas",
        "A biotecnologia branca se refere à aplicação de biotecnologia em processos industriais, como a produção de bioenergia e biocombustíveis",
        "A biotecnologia vermelha é usada na área médica, incluindo o desenvolvimento de novos tratamentos e vacinas",
        "A biotecnologia azul envolve a utilização de recursos biológicos marinhos, como algas e micro-organismos marinhos, para produtos e processos inovadores",
        "A clonagem terapêutica, uma área da biotecnologia, tem o potencial de regenerar tecidos e órgãos para transplantes",
        "A biotecnologia pode ser usada para tratar doenças genéticas, como a terapia genética, onde os genes defeituosos são corrigidos",
        "A biotecnologia de precisão envolve a edição do DNA de organismos de forma mais eficiente, utilizando tecnologias como CRISPR-Cas9",
        "Os biocombustíveis, como o etanol e o biodiesel, são produzidos a partir de biomassa e podem substituir combustíveis fósseis",
        "A biotecnologia aplicada à saúde também envolve o desenvolvimento de vacinas, como as vacinas de mRNA utilizadas para combater a COVID-19",
        "A bioinformática é uma área da biotecnologia que utiliza técnicas de computação para analisar dados biológicos e genômicos",
        "A biotecnologia ambiental inclui a utilização de micro-organismos para limpar poluentes, como o tratamento de águas e solos contaminados",
        "A biotecnologia de alimentos envolve a manipulação de organismos para melhorar o sabor, a nutrição e a durabilidade dos alimentos",
        "A produção de alimentos fermentados, como queijo e iogurte, é um exemplo de biotecnologia tradicional",
        "A biotecnologia também é fundamental no desenvolvimento de biossensores para diagnosticar doenças e monitorar a saúde de forma rápida e precisa",
        "A biotecnologia pode ajudar a combater a mudança climática, criando soluções para a captura de carbono e a remoção de poluentes",
        "A terapia genética utiliza a biotecnologia para introduzir ou modificar genes em células para tratar doenças genéticas",
        "Organismos modificados geneticamente (OGMs) também são usados para criar medicamentos e vacinas mais eficazes e em maior escala",
        "A biotecnologia permite a produção de enzimas e hormônios que podem ser utilizados para tratamentos médicos e industriais",
        "A biotecnologia pode transformar resíduos orgânicos em novos produtos, como plásticos biodegradáveis e alimentos para animais",
        "A produção de anticorpos monoclonais por biotecnologia é uma inovação importante para o tratamento de doenças como câncer e doenças autoimunes",
        "A biotecnologia pode ser usada para a produção de materiais biocompatíveis, como tecidos e órgãos artificiais",
        "O desenvolvimento de terapias baseadas em células-tronco é uma aplicação promissora da biotecnologia na medicina regenerativa",
        "A biotecnologia também pode ser aplicada no desenvolvimento de novos biomateriais e dispositivos médicos, como próteses e implantes",
        "A biotecnologia molecular pode ser usada para descobrir novas drogas e tratamentos mais eficazes e personalizados",
        "A biotecnologia aplicada à agricultura também inclui a criação de culturas resistentes a secas e outras condições climáticas adversas",
        "A biotecnologia de plantas pode criar variedades agrícolas mais nutritivas, ajudando a combater a fome e a desnutrição mundial",
        "Os biofármacos, produzidos por organismos vivos, são uma classe de medicamentos inovadores usados no tratamento de doenças graves",
        "A biotecnologia está ajudando na produção de alimentos mais sustentáveis, como o aumento da eficiência da produção de proteínas vegetais",
        "A biotecnologia em saúde também envolve o uso de terapias baseadas em RNA mensageiro para tratar doenças virais e genéticas",
        "A biotecnologia marinha explora recursos biológicos dos oceanos para desenvolver novos medicamentos e produtos industriais",
        "Além da medicina, a biotecnologia é aplicada em cosméticos e produtos de cuidado pessoal, criando fórmulas mais eficientes e seguras",
        "A biotecnologia também pode ser usada para desenvolver vacinas mais rápidas e acessíveis, como as vacinas de DNA e RNA",
        "O uso de microrganismos na biotecnologia para a produção de alimentos e bebidas é uma prática milenar e ainda muito relevante",
        "A biotecnologia é uma área interdisciplinar, combinando biologia, química, física e ciência da computação para resolver problemas complexos"

    ],
    "Educação e Tecnologia (EdTech)": [
        "A tecnologia educacional (EdTech) está transformando a forma como alunos e professores interagem no ambiente de aprendizagem",
        "Plataformas de aprendizagem online, como Coursera e Khan Academy, permitem que estudantes de todo o mundo acessem cursos de qualidade",
        "A realidade aumentada (AR) e a realidade virtual (VR) estão sendo usadas para criar experiências de aprendizagem imersivas e interativas",
        "O uso de jogos educacionais está ganhando popularidade por tornar o aprendizado mais envolvente e dinâmico",
        "A inteligência artificial (IA) está sendo usada em ferramentas de personalização do aprendizado, adaptando o conteúdo de acordo com o progresso do aluno",
        "Educação personalizada usa dados para oferecer trajetórias de aprendizado ajustadas às necessidades individuais dos estudantes",
        "Os MOOCs (Massive Open Online Courses) oferecem cursos gratuitos ou a preços acessíveis de universidades e instituições renomadas ao redor do mundo",
        "A gamificação no ensino incentiva os alunos a aprenderem por meio de desafios, recompensas e competições amigáveis",
        "As plataformas de e-learning oferecem flexibilidade de horário, permitindo que os alunos aprendam no seu próprio ritmo e em qualquer lugar",
        "As ferramentas de colaboração online, como Google Classroom e Microsoft Teams, facilitam a comunicação e o trabalho em grupo entre alunos e professores",
        "O uso de análises de dados na educação permite acompanhar o desempenho dos alunos em tempo real e ajustar as estratégias pedagógicas",
        "A inteligência artificial pode ajudar a identificar as dificuldades de aprendizagem dos alunos e sugerir recursos personalizados para melhorar seu desempenho",
        "As tecnologias de aprendizado adaptativo ajustam o conteúdo e o ritmo de aprendizagem com base nas respostas dos alunos, promovendo um ensino mais eficaz",
        "A tecnologia no ensino superior está ajudando as universidades a ampliar seu alcance, oferecendo cursos online e programas de graduação a distância",
        "O uso de assistentes virtuais e chatbots em plataformas de aprendizado permite tirar dúvidas dos alunos de forma instantânea e eficaz",
        "A impressão 3D está sendo aplicada em algumas escolas para ensinar conceitos de design, engenharia e ciências de forma prática e criativa",
        "As plataformas de microaprendizado oferecem conteúdo em pequenas doses, permitindo que os alunos aprendam rapidamente e em intervalos curtos",
        "A educação móvel (m-learning) permite que os alunos acessem conteúdo educacional por meio de smartphones e tablets em qualquer lugar",
        "Ferramentas de realidade aumentada e realidade virtual (AR/VR) estão transformando as aulas de ciências, história e até matemática com experiências imersivas",
        "A tecnologia de gravação e transmissão de aulas ao vivo (streaming) permite que as aulas cheguem a um público maior e diversificado",
        "A utilização de tecnologia assistiva ajuda a tornar a educação mais inclusiva para estudantes com deficiência, como softwares de leitura e legendagem",
        "As plataformas de feedback instantâneo permitem que os professores recebam respostas em tempo real dos alunos, ajudando a ajustar o ensino",
        "Aplicativos educacionais para crianças, como Khan Academy Kids e Duolingo, oferecem maneiras lúdicas e interativas de aprender",
        "O ensino de habilidades digitais, como programação e design, se tornou uma parte importante dos currículos escolares em todo o mundo",
        "A IA no EdTech pode automatizar tarefas administrativas, liberando tempo para os professores se concentrarem em atividades pedagógicas",
        "As ferramentas de videoconferência, como Zoom e Google Meet, foram integradas ao ensino remoto, oferecendo flexibilidade de acesso às aulas",
        "As plataformas de análise de dados educacionais ajudam a prever o desempenho futuro dos alunos e a identificar áreas que precisam de mais atenção",
        "Algumas escolas estão usando plataformas de crowdsourcing para promover o aprendizado colaborativo entre alunos de diferentes escolas e regiões",
        "A tecnologia de blockchain está começando a ser explorada para armazenar e validar diplomas e registros educacionais de forma segura e descentralizada",
        "O uso de plataformas de autoria e criação de conteúdo permite que os professores criem materiais didáticos personalizados para suas aulas",
        "As escolas estão integrando a programação de computadores no currículo, ensinando os alunos a codificar desde a educação infantil",
        "Além de professores, os alunos também têm acesso a tutores online, que podem ajudar a esclarecer dúvidas fora do horário escolar",
        "O ensino de ciências, tecnologia, engenharia e matemática (STEM) está sendo potencializado com o uso de kits de robótica e programação",
        "As ferramentas de realidade aumentada (AR) podem criar experiências de aprendizagem de ciências naturais, permitindo que os alunos vejam estruturas celulares ou planetas em 3D",
        "O uso de e-books e audiobooks permite que os alunos acessem conteúdo de leitura de maneira mais acessível e interativa",
        "As ferramentas de avaliação digital permitem uma correção mais rápida e precisa, com a possibilidade de feedback instantâneo aos alunos",
        "A tecnologia permite que os alunos participem de experiências internacionais de aprendizado, por meio de intercâmbios virtuais e projetos colaborativos online",
        "O uso de plataformas de conteúdo digital permite que escolas em regiões remotas tenham acesso a materiais didáticos de alta qualidade",
        "As bibliotecas digitais oferecem acesso a uma enorme quantidade de recursos acadêmicos e literários, democratizando o acesso ao conhecimento",
        "O uso de redes sociais na educação facilita a comunicação e o compartilhamento de recursos entre estudantes e professores de diferentes locais",
        "As universidades estão implementando plataformas de aprendizagem baseadas em IA para monitorar o progresso do aluno e recomendar cursos de forma personalizada",
        "Os softwares de simulação ajudam a ensinar habilidades práticas em áreas como medicina, engenharia e arquitetura sem a necessidade de equipamentos físicos",
        "As inovações tecnológicas em educação podem promover um aprendizado mais inclusivo, interativo e acessível para estudantes de todas as idades"

    ],
    "Tecnologia Espacial": [
        "A tecnologia espacial tem impulsionado inovações em áreas como telecomunicações, meteorologia, navegação e até agricultura",
        "Os satélites artificiais são usados para monitorar o clima, melhorar a previsão do tempo e estudar fenômenos meteorológicos extremos",
        "Os foguetes são a principal tecnologia utilizada para enviar cargas e pessoas para o espaço, com os lançamentos se tornando mais frequentes e acessíveis",
        "A exploração de Marte é uma das grandes frentes da tecnologia espacial, com missões como o rover Perseverance da NASA investigando o planeta vermelho",
        "A Estação Espacial Internacional (ISS) é um laboratório orbitando a Terra, onde astronautas realizam experimentos científicos em microgravidade",
        "A tecnologia de propulsão iônica está sendo desenvolvida para viagens espaciais mais eficientes, utilizando campos elétricos para acelerar partículas carregadas",
        "Os telescópios espaciais, como o Hubble, ajudam a capturar imagens detalhadas do espaço profundo e a expandir nosso conhecimento do universo",
        "A tecnologia de radar espacial permite estudar a superfície de planetas e luas, revelando informações sobre sua geologia e composição",
        "O estudo de asteroides e cometas é vital para entender a formação do sistema solar e os riscos que esses corpos celestes representam",
        "O Sistema de Posicionamento Global (GPS) é uma aplicação direta da tecnologia espacial, utilizando satélites para determinar a localização na Terra",
        "O telescópio espacial James Webb, lançado em 2021, promete revolucionar nossa compreensão do universo com observações mais nítidas e profundas",
        "A tecnologia espacial tem contribuído para a criação de sistemas de comunicação por satélite que conectam até as regiões mais remotas do planeta",
        "Os veículos espaciais reutilizáveis, como o foguete Falcon 9 da SpaceX, estão tornando os lançamentos mais baratos e frequentes",
        "A exploração lunar está sendo revitalizada, com missões futuras planejando estabelecer bases permanentes para exploração científica e mineração de recursos",
        "Os telescópios de raios X e rádio telescópios ajudam a estudar fenômenos cósmicos como buracos negros, supernovas e pulsars",
        "Os satélites de observação da Terra ajudam a monitorar mudanças ambientais, desmatamento, e até detectar fontes de poluição",
        "As missões espaciais também estudam os efeitos da gravidade zero sobre o corpo humano, ajudando a entender melhor a saúde e os cuidados médicos",
        "A mineração de asteroides está sendo explorada como uma possível fonte de recursos valiosos, como metais raros e água, para suportar a exploração espacial futura",
        "O primeiro voo espacial tripulado foi realizado por Yuri Gagarin em 1961, e desde então a exploração humana do espaço se expandiu enormemente",
        "As viagens comerciais ao espaço estão se tornando mais comuns, com empresas como SpaceX, Blue Origin e Virgin Galactic oferecendo voos turísticos",
        "A tecnologia de comunicação via laser está sendo testada para transferir dados de forma mais rápida e eficiente entre satélites e estações terrestres",
        "Satélites de observação permitem monitorar desastres naturais em tempo real, como incêndios florestais, inundações e terremotos, auxiliando em esforços de socorro",
        "A robótica espacial tem sido essencial para missões automatizadas, com sondas e rovers explorando planetas e luas distantes sem a necessidade de presença humana",
        "A tecnologia de escudo térmico desenvolvida para proteger naves espaciais na reentrada atmosférica é crucial para a segurança das missões espaciais",
        "Os astronautas são treinados para viver em microgravidade e em ambientes isolados, o que é essencial para missões longas, como a viagem a Marte",
        "O conceito de 'colonização espacial' está sendo explorado, com a ideia de criar habitats humanos em outros planetas, como Marte ou luas de Júpiter e Saturno",
        "A fotografia espacial tem ajudado a mapear planetas, estrelas e galáxias, revelando a vastidão e a complexidade do universo",
        "As missões interplanetárias estão se tornando mais frequentes, com sondas enviadas para estudar Vênus, Júpiter, Saturno e além",
        "A NASA está desenvolvendo tecnologias para possibilitar a exploração humana de Marte, incluindo sistemas de suporte à vida e propulsão avançada",
        "As redes de satélites em órbita de baixa altitude (LEO) estão sendo usadas para criar internet global, melhorando a conectividade em áreas isoladas",
        "Pesquisas espaciais ajudam a entender a origem do universo, a formação das estrelas e os processos que acontecem em buracos negros e outros corpos celestes",
        "O uso de tecnologia de impressão 3D no espaço está permitindo a construção de peças e ferramentas para missões espaciais, reduzindo a necessidade de transportar materiais",
        "A Agência Espacial Europeia (ESA) e a NASA têm projetos conjuntos para explorar luas de Júpiter, como Europa, que possui um oceano subterrâneo que pode abrigar vida",
        "A astrobiologia, o estudo da vida no universo, está sendo investigada por meio de missões espaciais para entender se a vida poderia existir em outros planetas",
        "As tecnologias espaciais também têm aplicações na Terra, como no desenvolvimento de sistemas de GPS, previsão do tempo e diagnóstico médico",
        "A utilização de satélites para monitoramento de desmatamento e mudanças climáticas tem ajudado no combate ao aquecimento global e preservação ambiental",
        "Pesquisas em física espacial estão ajudando a entender as radiações cósmicas e seus efeitos sobre a saúde humana e as tecnologias utilizadas no espaço"

    ],
    "Tecnologia em Saúde (HealthTech)": [
        "A tecnologia em saúde, também conhecida como HealthTech, está revolucionando o cuidado com os pacientes, desde diagnósticos até tratamentos personalizados",
        "A telemedicina permite que médicos atendam pacientes à distância, proporcionando acesso a cuidados médicos em áreas remotas ou para pessoas com mobilidade limitada",
        "Dispositivos vestíveis, como smartwatches, monitoram sinais vitais, como frequência cardíaca, níveis de oxigênio e até ritmo de sono, para fornecer dados em tempo real sobre a saúde",
        "As plataformas de registros eletrônicos de saúde (EHR) ajudam os profissionais médicos a acessar rapidamente os dados dos pacientes, melhorando a eficiência e a precisão dos diagnósticos",
        "A inteligência artificial (IA) está sendo usada para desenvolver sistemas de diagnóstico mais rápidos e precisos, como a detecção precoce de câncer em exames de imagem",
        "A impressão 3D está sendo aplicada na medicina para criar próteses personalizadas, modelos anatômicos para planejamento cirúrgico e até mesmo órgãos humanos artificiais",
        "A análise de big data está sendo usada para identificar padrões de doenças, melhorar tratamentos e prever surtos de epidemias",
        "As terapias genéticas estão sendo exploradas para tratar doenças genéticas raras, corrigindo ou substituindo genes defeituosos diretamente nas células do paciente",
        "A robótica está transformando a cirurgia, com sistemas de cirurgia assistida por robôs oferecendo maior precisão e controle durante os procedimentos",
        "A inteligência artificial no diagnóstico médico está ajudando a identificar doenças de forma mais precoce e com maior precisão, muitas vezes superando a acurácia dos médicos humanos",
        "A saúde digital está promovendo a criação de aplicativos e dispositivos para monitoramento contínuo da saúde, como apps para controle de diabetes e hipertensão",
        "A tecnologia de realidade aumentada (AR) está sendo utilizada em treinamentos médicos, proporcionando simulações realistas de procedimentos e técnicas cirúrgicas",
        "Plataformas de saúde mental online, como terapia virtual e suporte psicológico remoto, estão se tornando uma opção popular para tratar transtornos mentais",
        "A nanotecnologia está sendo usada para desenvolver tratamentos mais eficazes e específicos para doenças, como medicamentos que podem atingir diretamente células doentes",
        "O uso de drones no setor de saúde está ajudando na entrega rápida de medicamentos e suprimentos médicos em áreas de difícil acesso",
        "A tecnologia de wearables também está sendo usada para monitorar pacientes com doenças crônicas, enviando alertas para os profissionais de saúde em caso de alterações nos sinais vitais",
        "As vacinas de mRNA, como as utilizadas para combater a COVID-19, são um exemplo inovador de tecnologia em saúde que utiliza a engenharia genética para ensinar o sistema imunológico a combater infecções",
        "As plataformas de saúde digital estão melhorando o acesso à educação e informações médicas, tornando-as mais acessíveis para populações globalmente",
        "Dispositivos de monitoramento remoto permitem que os pacientes sejam acompanhados de forma contínua, sem a necessidade de visitas frequentes ao hospital",
        "Os algoritmos de IA estão sendo usados para prever e personalizar planos de tratamento, considerando o histórico médico, genética e dados do paciente em tempo real",
        "A bioimpressão 3D está avançando para a criação de tecidos humanos, e, no futuro, pode permitir a impressão de órgãos inteiros para transplante",
        "A análise preditiva está sendo usada para identificar fatores de risco de doenças, como doenças cardíacas e diabetes, antes que os sintomas apareçam",
        "Os aplicativos de saúde estão permitindo que os usuários monitorem sua dieta, atividade física, saúde mental e outros aspectos de seu bem-estar, com feedback instantâneo",
        "A robótica de assistência está sendo usada para ajudar pacientes com mobilidade limitada a realizar tarefas diárias, proporcionando mais autonomia",
        "As tecnologias de inteligência artificial podem detectar sinais precoces de doenças como Alzheimer, analisando mudanças sutis no comportamento ou na fala dos pacientes",
        "A realidade virtual (VR) está sendo aplicada na reabilitação de pacientes, criando simulações de exercícios e terapias para acelerar a recuperação após lesões",
        "A tecnologia de sensores vestíveis, como os usados para monitorar o nível de glicose em tempo real, está transformando o manejo de doenças como diabetes",
        "O uso de blockchain está ajudando a criar registros de saúde digitais mais seguros e imutáveis, protegendo os dados dos pacientes contra acessos não autorizados",
        "A análise de imagens médicas por IA está melhorando a precisão dos diagnósticos de doenças como câncer, doenças cardíacas e distúrbios neurológicos",
        "Plataformas de saúde online estão oferecendo consultas médicas, prescrições e diagnósticos via videoconferência, tornando o acesso ao cuidado mais eficiente",
        "Os sistemas de inteligência artificial também estão sendo usados para personalizar a medicina, ajustando os tratamentos com base nas características genéticas e biomédicas de cada paciente",
        "O monitoramento remoto de pacientes está ajudando a reduzir a sobrecarga nos hospitais, permitindo que os médicos acompanhem a recuperação e as condições dos pacientes em casa",
        "As tecnologias de simulação estão ajudando a treinar médicos e enfermeiros em procedimentos complexos e raros, sem a necessidade de práticas com pacientes reais",
        "A medicina de precisão, que utiliza dados genéticos e moleculares para criar tratamentos personalizados, está revolucionando a forma como as doenças são tratadas",
        "A tecnologia de análise de dados em tempo real está ajudando a prever a evolução de pandemias e surtos de doenças, auxiliando na tomada de decisões rápidas de saúde pública",
        "Plataformas de saúde móvel estão democratizando o acesso a cuidados médicos, permitindo consultas médicas online em tempo real em qualquer lugar do mundo",
        "O uso de chatbots de saúde está permitindo que pacientes tirem dúvidas comuns sobre seus sintomas e condições de saúde, proporcionando orientação imediata"

    ] 


};

const greetings = ["oi", "olá", "tudo bem", "e aí",];
const goodbyes = ["tchau", "adeus", "até logo", "falou", "até mais",];

let context = "Default"; // Variável para armazenar o último contexto

sendButton.addEventListener("click", enviarMensagem);
input.addEventListener("keyup", (e) => {
    if (e.key === "Enter") {
        enviarMensagem();
    }
});

function enviarMensagem() {
    if (input.value.trim() !== "") {
        const userMessage = input.value.trim().toLowerCase();
        adicionarMensagem(userMessage, "user-message");

        // Verifica se é uma saudação ou despedida
        if (isGreeting(userMessage)) {
            setTimeout(() => {
                adicionarMensagem("Olá! Como posso ajudar?" || "b", "bot-message");
                messageList.scrollTop = messageList.scrollHeight;
            }, 1000);
        } else if (isGoodbye(userMessage)) {
            setTimeout(() => {
                adicionarMensagem("Até logo! Tenha um ótimo dia!", "bot-message");
                messageList.scrollTop = messageList.scrollHeight;
            }, 1000);
        } else {
            // Detecção de temas caso não seja saudação ou despedida
            let intent = "Default";

            // Detecção de temas
            for (let topic in responses) {
                if (userMessage.includes(topic.toLowerCase())) {
                    intent = topic;
                    break;
                }
            }

            context = intent; // Atualiza o contexto com o intent atual

            input.value = "";

            setTimeout(() => {
                const resposta = obterResposta(intent);
                adicionarMensagem(resposta, "bot-message");
                messageList.scrollTop = messageList.scrollHeight;
            }, 2000);
        }
    }
}

function adicionarMensagem(texto, classe) {
    const message = document.createElement("div");
    message.classList.add("chat-message", classe);
    message.innerHTML = `<div class="chat-message-text">${texto}</div>`;
    messageList.appendChild(message);
}

function obterResposta(intent) {
    const respostasDisponiveis = responses[intent];
    if (respostasDisponiveis && respostasDisponiveis.length > 0) {
        const indiceAleatorio = Math.floor(Math.random() * respostasDisponiveis.length);
        return respostasDisponiveis[indiceAleatorio];
    } else {
        return "Desculpe, não tenho uma resposta para isso. Tente outro tema.";
    }
}

// Funções para identificar saudação e despedida
function isGreeting(message) {
    return greetings.some(greeting => message.includes(greeting));
}

function isGoodbye(message) {
    return goodbyes.some(goodbye => message.includes(goodbye));
}

// Adiciona um evento de clique em cada item de tema
document.querySelectorAll(".side-box li").forEach(item => {
    item.addEventListener("click", () => {
        const theme = item.innerText;  // Obtém o nome do tema clicado
        const response = obterResposta(theme);  // Pega a curiosidade relacionada ao tema
        adicionarMensagem(response, "bot-message");  // Exibe no chat
    });
});

function logout() {
    // Aqui você pode adicionar a lógica de logout, como limpar informações no localStorage, etc.
    alert("Você foi desconectado!");
    // Redirecionando para a página de login (exemplo)
    window.location.href = "login.html"; // Ajuste o caminho conforme necessário
}
